class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.26.tar.gz"
  sha256 "64d5afccb64c9f070d68c689fb3f2acded24f81ed349afd8a48cd534e5c0a16c"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "54046b1755146f227ea5bd8563cc5d6e8663eea3020cc624b0a85975f41d6405"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "54046b1755146f227ea5bd8563cc5d6e8663eea3020cc624b0a85975f41d6405"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "54046b1755146f227ea5bd8563cc5d6e8663eea3020cc624b0a85975f41d6405"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "866447dd1de3b074ae32abdd3c8bd0e2a68297278c92e9858413c156d7cf83cd"
    sha256 cellar: :any,                 x86_64_linux:  "c5ddfbbc695a0e8dd6ded068f8583ecbde30c65d0a48916094d4cefbf9fc351f"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
