class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.24.tar.gz"
  sha256 "a6e547f632636578a023161c391afa671ac6c1afa870599d79d4104b6af09c30"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "1c32f5d10a73a490d92fb1a6287a8af2ab0f5e4b5fc6bd77632d47160923d656"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "1c32f5d10a73a490d92fb1a6287a8af2ab0f5e4b5fc6bd77632d47160923d656"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "1c32f5d10a73a490d92fb1a6287a8af2ab0f5e4b5fc6bd77632d47160923d656"
    sha256 cellar: :any_skip_relocation, sonoma:        "a95ebeab8ec6a5f9fd861fa507fe8200650ae179053b8cabd83e8a0542b60be7"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "85987272cadd2b097da6d8da7d7f7ee7a69e271c9849cede08f366f760421f01"
    sha256 cellar: :any,                 x86_64_linux:  "1ad29bb5a650cb2442568e6c02191659817a7f4fd2a6d3be3744426725e5832f"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
