class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.12.7.tar.gz"
  sha256 "4a0941ef8f8131bf15f1dec50c96a17d94aae732ff8e9cb3a32c9d4f86d360fe"
  license any_of: ["Apache-2.0", "MIT"]
  compatibility_version 1
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "8449162d1e9cb3a46329ef44b50b2d20c0d5f9392a5ac0a3a6934dbb646e152a"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "457face28a088dfbcbcc1120d725ba3d2ef2959a4a24ad75590aaf5eede39ba4"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "9ce46a9ac5f098e3d0475e6512108634f460409fca4b7fc64b72035304f312bd"
    sha256 cellar: :any_skip_relocation, sonoma:        "54c2d3269a0979fcae9960fadc29565b2fa340b170db8dbb0fa6832cfda6c77d"
    sha256 cellar: :any,                 arm64_linux:   "3029b9199355b728b812af83114eaf66dfa2108d658787c07ccaa1a1eff732cd"
    sha256 cellar: :any,                 x86_64_linux:  "e3171cfd41ea9da8c11aca6b8f1c612924f1571d131853c289e4fda73c7bfd01"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  # downloads crates on install and wheels in test
  deny_network_access! :postinstall

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
